### ISSUE TITLE
Dependencies

### ISSUE THREAD

**Issue by mariansam** [bakalari-api/php-bakalari-utils#1]
Když jsem to spustli pomocí `php -S 0.0.0.0:8080` a vyzkoušel, dostal jsem *DOMElement not found*. Na Fedoře je potřeba `sudo dnf install php-xml`. Nevím jak na Debianu (a podobných) a už vůbec nevím jak na Windowsu. Bylo by potřeba to zjistit a doplnit do readme.

**Comment by ejdrien** [comment]
Tak na Windowsech se většinou k funkcni php stránek používá nějaký program jako XAMPP nebo WAMP apod., se kterými to funguje bez problemů. Taktéž pokud by si toto někdo dal na svoje webové stránky, které má u nějakého hostingu, tak na něm to určitě na 99,99% bude šlapat bez problému, protože takovéto věci tam bývají často předinstalované. Hold na Linuxu to nepůjde hned, ale věř mi, že pokud někdo používá Linux, tak s tímhle rozhodně nebude problém a beztak už to bude mít nainstalované.

**Comment by mariansam** [comment]
Tak já mám Linux, mám PHP a neměl jsem PHP-XML... ale i tak vyřešeno za minutku.

**Comment by JosefKuchar** [comment]
Můžeš to dát do readme

**Comment by mariansam** [comment]
Okey, přidáno, zavírám
